# Generated by Django 4.2.14 on 2024-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
    ]
