# Generated by Django 4.2.14 on 2024-07-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_sermon_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="image",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="preacher_info",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
